CREATE TABLE IF NOT EXISTS Contain (
    O_ID INT NOT NULL,
    B_ID INT NOT NULL,
    PRIMARY KEY (O_ID , B_ID),
    FOREIGN KEY (O_ID) REFERENCES Orders (O_ID),
    FOREIGN KEY (B_ID)  REFERENCES Books (B_ID)
);
