CREATE TABLE IF NOT EXISTS Payments (
    P_ID INT NOT NULL UNIQUE,
    C_ID INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    payMethod VARCHAR(50) NOT NULL,
    paymentdate DATE NOT NULL,
    O_ID INT NOT NULL,
    PRIMARY KEY (P_ID),
    FOREIGN KEY (C_ID) REFERENCES Customers(C_ID),
    FOREIGN KEY (O_ID) REFERENCES Orders(O_ID)
);
